### PR TITLE
Test Program Updates 2020-11-06 16:58:51

### PR DESCRIPTION
**Pull request by sickcodes**
# Summary
< a quick summary of the associated pull request >

# Quality Assurance Checklist
< confirmation of this pull request meeting the following requirements, prior to merge >
| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty    |     |
| Disclosure terms are publicly available |     |
| Public URL                              |     |
| Single Source, or all sources appended  |     |
| Submission follows the [Diodb schema](https://github.com/disclose/diodb/blob/master/program-list/program-list-schema.json)     |     |

### CODE REVIEW

**Comment by prodigysml** [comment]
@yesnet0, this majorly LGTM, but worth noting that it adds in all fields including non-required ones as empty strings and stuff.

**Comment by sickcodes** [comment]
Don't accept this PR yet as it's missing some fields, I'll add shortly.


However I think if there's empty fields, it will encourage people to submit PRs to correct those values, what do you think? @prodigysml

**Comment by prodigysml** [comment]
I think that's a great idea! Anything to encourage gathering more information for the data set!

**Comment by yesnet0** [comment]
Re missing fields: 100%. That's part of the goal, encourage program owners and other contributors to proactively contribute and "fill in the blanks".

**Comment by sickcodes** [comment]
Sounds good, I also think sort the JSON alphabetically on the program name.

I can do it but if one of you guys want to submit a PR to sort the current json, that will make this PR will look more itemized with the ability to pick differences line by line in the git diff.

**Comment by prodigysml** [comment]
Just to clarify @sickcodes, it would be helpful to have the current JSON in master right now, to be sorted alphabetically, by the program name? If so, I can def submit that for you!

**Comment by sickcodes** [comment]
Yes sir! I'll submit a small script to the other repo that will sort it shortly as I've already done it 😂

**Comment by sickcodes** [comment]
Sorted  + Added Sorting tool https://github.com/disclose/diodb/pull/260

No fields are missing, it just pulls the JSON into a pandas dataframe and exports it again.

**Pull request merged**
