### PR TITLE
Adding some Aussie VDPs

### PR DESCRIPTION
**Pull request by bad5ect0r**
# Summary

Added a few Aussie companies and departments that have a VDP.

# Quality Assurance Checklist

| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty or vulnerability disclosure program    |  Y    |
| Disclosure policy is publicly available |  Y   |
| Public URL                              |   Y  |
| Submission follows the [Diodb schema](https://github.com/disclose/diodb/blob/master/program-list/program-list-schema.json)     |  Y   |

Your Twitter handle (Optional): @bad5ect0r

### CODE REVIEW

**Comment by bad5ect0r** [comment]
Looks like the validate-links-job is failing on preexisting entries. Should I fix these too before the PR can be accepted?

**Comment by prodigysml** [comment]
Hey @bad5ect0r, that should be another PR. It's an issue we plan to fix, but don't have the bandwidth atm. If you're game, we'd really appreciate any help!

**Review by yesnet0 — COMMENTED** [review]
Hey @bad5ect0r - For Buildexact the "contact_url" would be https://www.buildxact.com.au/responsible-disclosure since the submission form is embedded. Could you please update? Thanks!

**Review by yesnet0 — APPROVED** [review]
Hey @bad5ect0r - For DoH safe_harbor would be "none" since protection is inferred, but not stated.

**Comment by yesnet0** [comment]
Thanks @bad5ect0r!

**Pull request merged**
