### PR TITLE
Add Gitcoin and zkSync

### PR DESCRIPTION
**Pull request by nikitastupin**
# Summary

- Change formatting rules according to `program-list.json`
- Add Gitcoin and zkSync
- Apply `sort-diodb.py` formatting

# Quality Assurance Checklist

| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty or vulnerability disclosure program    | Y |
| Disclosure policy is publicly available | Y |
| Public URL                              | Y |
| Submission follows the [Diodb schema](https://github.com/disclose/diodb/blob/master/program-list-schema.json)     | Y |

Your Twitter handle (Optional): @_nikitastupin

### CODE REVIEW

**Comment by nikitastupin** [comment]
It seems that `duplicate-check` workflow is reporting a lot of false positives. May be we should disable it until it's fixed?

**Comment by sickcodes** [comment]
I'll fix this up today on your branch and merge 🚀

**Review by yesnet0 — APPROVED** [review]
Thanks @nikitastupin!

**Comment by nikitastupin** [comment]
Closed by #381

**Pull request closed without merging**
