### PR TITLE
Added HackerRank RDP

### PR DESCRIPTION
**Pull request by swapHR**
# Summary
Updated HackerRank Responsible Disclosure 

# Quality Assurance Checklist
< Confirmation of this pull request meeting the following requirements, prior to merge > 

| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty or vulnerability disclosure program    |  Y  |
| Disclosure policy is publicly available |  Y  |
| Public URL                              |   Y  |
| Submission follows the [Diodb schema](https://github.com/disclose/diodb/blob/master/program-list-schema.json)     | Y |

Your Twitter handle (Optional): swapmaurya20

### CODE REVIEW

**Review by yesnet0 — CHANGES_REQUESTED** [review]
You've listed the program as "Partial" safe harbor but there is no statement of good faith within the policy. In its current form it is "None". Please amend the PR.

**Comment by swapHR** [comment]
edited safe harbour and also added contact email

**Review by yesnet0 — COMMENTED** [review]
LGTM!

**Comment by swapHR** [comment]
Merg Conflicts Resolved

**Comment by sickcodes** [comment]
```
      "policy_url_status": "alive",
<<<<<<< HEAD
      "contact_email": "security@rewind.com"
=======
      "contact_email": "vdp@rewind.io"
>>>>>>> 8a63d3465891c9a80312a0810a282e60757be3e9
   },
   {

```


```
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 32905 column 1 (char 987040)


Error: Unexpected token < in JSON at position 987040

```

**Pull request merged**
