### PR TITLE
Update bug-bounty-list.json

### PR DESCRIPTION
**Pull request by meszicsaba**
Added in Antavo Loyalty Management Platforms BBP

# Summary
< A quick summary of the associated pull request >

# Quality Assurance Checklist
< Confirmation of this pull request meeting the following requirements, prior to merge > 

| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty or vulnerability disclosure program    |     |
| Disclosure policy is publicly available |     |
| Public URL                              |     |
| Submission follows the [Diodb schema](https://github.com/disclose/diodb/blob/master/program-list-schema.json)     |     |

Your Twitter handle (Optional):

### CODE REVIEW

**Review by yesnet0 — CHANGES_REQUESTED** [review]
Please post the link for the actual policy itself. This currently links to a list of programs. The policy needs to be publicly readable to be considered.

**Comment by meszicsaba** [comment]
Hi,

Our platform is design that way that only registered ethical hackers can see the details of the policy - accepting our Terms of service, Testing policy and Data protection policy.

Can you please advise what are the options here? Can we either use the added link or can this program be on the list with our platforms main page’s URL?

Thanks,
Csaba
________________________________
Feladó: cje ***@***.***>
Elküldte: szombat, július 17, 2021 2:37 du.
Címzett: disclose/diodb
Másolatot kap: Mészáros Csaba; Author
Tárgy: Re: [disclose/diodb] Update bug-bounty-list.json (#320)


@yesnet0 requested changes on this pull request.

Please post the link for the actual policy itself. This currently links to a list of programs. The policy needs to be publicly readable to be considered.

**Comment by yesnet0** [comment]
Understood. The disclose.io Project doesn't consider what you've described as a true vulnerability disclosure policy, since VDPs should be accessible and available to anyone on the Internet who wishes to report an issue. Instead, I'd suggest adding your platform to the list here: https://github.com/disclose/bug-bounty-platforms

**Comment by meszicsaba** [comment]
Yes, indeed, this is a bug bounty program not a vdp, but I thought it is also possible to list bbp here. Thanks for the other link, I will try to szbmit there.

Regards,
Csaba
________________________________
Feladó: cje ***@***.***>
Elküldve: Saturday, July 24, 2021 8:37:17 AM
Címzett: disclose/diodb ***@***.***>
Másolatot kap: Mészáros Csaba ***@***.***>; Author ***@***.***>
Tárgy: Re: [disclose/diodb] Update bug-bounty-list.json (#320)


Understood. The disclose.io Project doesn't consider what you've described as a true vulnerability disclosure policy, since VDPs should be accessible and available to anyone on the Internet who wishes to report an issue. Instead, I'd suggest adding your platform to the list here: https://github.com/disclose/bug-bounty-platforms

**Pull request closed without merging**
