### PR TITLE
Add Orgnostic Inc. Vulnerability Policy Details

### PR DESCRIPTION
**Pull request by aleksandarristic**
# Summary
Adding Orgnostic Inc. Public Vulnerability Program

# Quality Assurance Checklist
< Confirmation of this pull request meeting the following requirements, prior to merge > 

| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty or vulnerability disclosure program    |  Y  |
| Disclosure policy is publicly available |  Y  |
| Public URL                              |  https://orgnostic.com/vulnerability-disclosure  |
| Submission follows the [Diodb schema](https://github.com/disclose/diodb/blob/master/program-list-schema.json)     |  Y  |

Your Twitter handle (Optional):

### CODE REVIEW

**Comment by nikitastupin** [comment]
Hey @aleksandarristic,

Thanks for your contribution!

Unfortunately, the https://orgnostic.com/vulnerability-disclosure page doesn't seem to work. Can you provide an alternative policy page?

**Comment by aleksandarristic** [comment]
Hi @nikitastupin, we had a reorg of our website just last week and not all pages were initially included. It's fixed now and should be working correctly. Could you please check now? Thanks!

**Comment by nikitastupin** [comment]
It works now!

There are two things needed to be done before merging: to rebase the PR and format the `program-list.json` file with the https://github.com/disclose/diodb#how-to-contribute command.

I couldn't do that in your fork because I don't have write access.

So I see three ways:

1. You could do rebase and formatting in your fork
2. You could open a new PR with formatted
3. I can open a new PR with the change (unfortunately, your GitHub account won't be referenced as contributor in this case)

**Comment by aleksandarristic** [comment]
Hey @nikitastupin - thanks for the pointers on how to get this done :)

So, I've rebased and formatted using the command you provided; please check it out now.

**Comment by nikitastupin** [comment]
Looks good, thanks!

**Comment by nikitastupin** [comment]
Arr, it seems that the rebase has removed some of the previous contributions 2b53a6302863bd723f3754bb44fec701320a2a4e

**Comment by aleksandarristic** [comment]
@nikitastupin awfully sorry for this. What can I do to help fix this?

**Comment by nikitastupin** [comment]
No worries! You can just open a new PR. Meanwhile I'll think how to better organize the file so that there is no need for rebase 😄

**Comment by aleksandarristic** [comment]
Hey @nikitastupin, just started off a fresh copy of master (did a reset on my own repo) and I've added our details again. Also did the format change with the jq tool. New PR is here: https://github.com/disclose/diodb/pull/383

**Comment by nikitastupin** [comment]
Thank you!

**Pull request merged**
