### PR TITLE
Add initial bug bounty list json

### PR DESCRIPTION
**Pull request by meszicsaba**
# Summary
We would like to add in Antavo Loyalty Management Platform to the Bug bounty list.

# Quality Assurance Checklist
< Confirmation of this pull request meeting the following requirements, prior to merge > 

| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty or vulnerability disclosure program    |     |
| Disclosure policy is publicly available |     |
| Public URL                              |     |
| Submission follows the [Diodb schema](https://github.com/disclose/diodb/blob/master/program-list-schema.json)     |     |

Your Twitter handle (Optional):

### CODE REVIEW

**Review by yesnet0 — CHANGES_REQUESTED** [review]
Hi @meszicsaba - Where is the publicly available policy for this program?

**Comment by meszicsaba** [comment]
Hi @yesnet0

I have seen on the page that other listed bug bounty programs neither have public websites (ones with envelope) only email address added in, so I thought to try and submit this. Antavo would like to be on this list as they have a bug bounty - can you help put them onto the list?
[cid:b3516639-9635-48eb-8558-fc13506452c2]

________________________________
Feladó: cje ***@***.***>
Elküldve: 2021. július 28., szerda 1:00
Címzett: disclose/diodb ***@***.***>
Másolatot kap: Mészáros Csaba ***@***.***>; Mention ***@***.***>
Tárgy: Re: [disclose/diodb] Add initial bug bounty list json (#322)


@yesnet0 requested changes on this pull request.

Hi @meszicsaba<https://github.com/meszicsaba> - Where is the publicly available policy for this program?

**Comment by yesnet0** [comment]
Sure - Please first set cash_reward and safe_harbor to NULL since these details aren't publicly available and thus cannot be confirmed by someone who uses the list.

**Comment by meszicsaba** [comment]
OK, I have modified that. Can you see the changes?
________________________________
Feladó: cje ***@***.***>
Elküldve: 2021. július 30., péntek 2:48
Címzett: disclose/diodb ***@***.***>
Másolatot kap: Mészáros Csaba ***@***.***>; Mention ***@***.***>
Tárgy: Re: [disclose/diodb] Add initial bug bounty list json (#322)


Sure - Please first set cash_reward and safe_harbor to NULL since these details aren't publicly available and thus cannot be confirmed by someone who uses the list.

**Review by yesnet0 — APPROVED** [review]

**Comment by meszicsaba** [comment]
Thank you. Do you know when this will be visible on this link?
https://www.bugcrowd.com/bug-bounty-list/


Kind regards,
Csaba
________________________________
Feladó: cje ***@***.***>
Elküldve: 2021. augusztus 2., hétfő 9:33
Címzett: disclose/diodb ***@***.***>
Másolatot kap: Mészáros Csaba ***@***.***>; Mention ***@***.***>
Tárgy: Re: [disclose/diodb] Add initial bug bounty list json (#322)


@yesnet0 approved this pull request.

**Comment by yesnet0** [comment]
Thanks @meszicsaba. The new merge looks good, but appears to have created conflicts. Can you please close this PR and re-pull? Thanks!

**Pull request closed without merging**
