### PR TITLE
Add Campaign Monitor, Emma, Liveclicker and Sailthru programs.

### PR DESCRIPTION
**Pull request by serdalis**
# Summary
Adding the Campaign Monitor, Emma, Liveclicker and Sailthru vulnerability programs to the program list.

# Quality Assurance Checklist
< Confirmation of this pull request meeting the following requirements, prior to merge > 

| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty or vulnerability disclosure program    |  Y |
| Disclosure policy is publicly available |  Y  |
| Public URL  CM                         |  https://www.campaignmonitor.com/policies/#safe-harbor-policy  |
| Public URL  EM                         |  https://myemma.com/trust/security/  |
| Public URL  LC                          |  https://www.liveclicker.com/privacy-policy/#priv-section-6  |
| Public URL  ST                          |  https://www.sailthru.com/trust/security/  |
| Submission follows the [Diodb schema](https://github.com/disclose/diodb/blob/master/program-list-schema.json)     |  Y  |

Your Twitter handle (Optional): 
None

### CODE REVIEW

**Comment by serdalis** [comment]
Might be some slight confusion on my part, we have a VDP which is from bugcrowd, but also the Safe Harbour Policy which is in Terms on our pages, have I linked the correct one in the program list?

**Comment by nikitastupin** [comment]
Hey @serdalis,

I think you've linked everything correctly. However, hackers might be confused seeing `offers_bounties: true` and `safe_harbor: full` on diodb page and not finding any reference to it in the policy.

Would you be willing to reference or note both rewards and safe harbor on the policy pages? Thanks!

**Comment by serdalis** [comment]
Hi @nikitastupin it took a little while but the bounty amounts are now on the submission forms.

Should be all good to go now!

**Comment by nikitastupin** [comment]
Hey @serdalis! Thank you! The bounty amounts looks good.

However, I think it'll also be helpful to reference the safe harbor terms at the policies. For example, we can add something like the following to the https://www.campaignmonitor.com/trust/report-a-vulnerability/ and other pages.

> ### Our Commitment to Researchers
> 
> Your research is covered by the [Safe Harbor Terms](https://www.campaignmonitor.com/policies/#safe-harbor-policy) policy.
> ...

**Pull request closed without merging**
